# Generated by Django 3.1.3 on 2020-11-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserDB.person')),
                ('Money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.CharField(max_length=1000)),
            ],
            bases=('UserDB.person',),
        ),
        migrations.AlterField(
            model_name='person',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
