# Generated by Django 3.1.3 on 2020-11-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDB', '0002_auto_20201107_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
