# Generated by Django 3.1.3 on 2020-11-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDB', '0003_remove_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Username',
        ),
    ]
