# Generated by Django 3.1.3 on 2020-11-08 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Task', models.CharField(choices=[('ML', 'Mow Lawn'), ('G', 'Groceries'), ('CH', 'Clean House'), ('SH', 'Snow Shoveling'), ('PH', 'Paint House'), ('RL', 'Rake Leaves')], max_length=2)),
                ('Address', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=120)),
                ('Province', models.CharField(max_length=2)),
                ('Postal', models.CharField(max_length=7)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.person')),
                ('Money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.CharField(max_length=1000)),
            ],
            bases=('tasks.person',),
        ),
    ]
