# Generated by Django 3.1.3 on 2020-11-12 23:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Task', models.CharField(choices=[('ML', 'Mow Lawn'), ('G', 'Groceries'), ('CH', 'Clean House'), ('SH', 'Snow Shoveling'), ('PH', 'Paint House'), ('RL', 'Rake Leaves'), ('M', 'Moving'), ('P', 'Plumbing')], max_length=2)),
                ('Price', models.IntegerField()),
                ('Phone', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(choices=[('ML', 'Mow Lawn'), ('G', 'Groceries'), ('CH', 'Clean House'), ('M', 'Moving'), ('P', 'Plumbing')], max_length=30)),
                ('Photo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/taskphotos/'), upload_to='/images/')),
                ('Link', models.CharField(max_length=50)),
            ],
        ),
    ]
